__set_git_status_content()
{
	REAL_DRAGON__GIT_STATUS_CONTENT=${${VCS_STATUS_LOCAL_BRANCH:-@${VCS_STATUS_COMMIT[1,8]}}//\%/%%}
	[[ -n "${VCS_STATUS_ACTION:-}" ]] && \
		REAL_DRAGON__GIT_STATUS_CONTENT+="%F{$DRAGON__GIT_ACTION_COLOR} ($VCS_STATUS_ACTION)%f"
}

__set_git_status_color()
{
	if [[ $VCS_STATUS_HAS_UNSTAGED -eq 1 || $VCS_STATUS_HAS_STAGED -eq 1 || $VCS_STATUS_HAS_UNTRACKED -eq 1 || $VCS_STATUS_HAS_CONFLICTED -eq 1 ]]; then
		REAL_DRAGON__GIT_STATUS_FOREGROUND_COLOR="$DRAGON__GIT_DIRTY_FOREGROUND_COLOR"
		REAL_DRAGON__GIT_STATUS_BACKGROUND_COLOR="$DRAGON__GIT_DIRTY_BACKGROUND_COLOR"
		REAL_DRAGON__GIT_STATUS_BOLD="$DRAGON__GIT_DIRTY_BOLD"
		REAL_DRAGON__GIT_STATUS_UNDERLINE="$DRAGON__GIT_DIRTY_UNDERLINE"
	else
		REAL_DRAGON__GIT_STATUS_FOREGROUND_COLOR="$DRAGON__GIT_CLEAN_FOREGROUND_COLOR"
		REAL_DRAGON__GIT_STATUS_BACKGROUND_COLOR="$DRAGON__GIT_CLEAN_BACKGROUND_COLOR"
		REAL_DRAGON__GIT_STATUS_BOLD="$DRAGON__GIT_CLEAN_BOLD"
		REAL_DRAGON__GIT_STATUS_UNDERLINE="$DRAGON__GIT_CLEAN_UNDERLINE"
	fi
}

__get_git_stash_count()
{
	GIT_STASH_STR=""
	! $DRAGON__ENABLE_GIT_STASH_COUNT && return
	(( VCS_STATUS_STASHES > 0 )) && GIT_STASH_STR="$DRAGON__GIT_STASH_SYMBOL$VCS_STATUS_STASHES"
}

__get_git_remote_state()
{
	GIT_REMOTE_STATE_STR=""
	! $DRAGON__ENABLE_GIT_REMOTE_STATE && return
	[[ -z $VCS_STATUS_REMOTE_NAME ]] && return  # no tracking branch

	local ahead="$VCS_STATUS_COMMITS_AHEAD"
	local behind="$VCS_STATUS_COMMITS_BEHIND"

	if (( ahead == 0 && behind == 0 )); then
		GIT_REMOTE_STATE_STR="$DRAGON__GIT_REMOTE_SYNCED_SYMBOL"
	else
		(( ahead  > 0 )) && GIT_REMOTE_STATE_STR+="$DRAGON__GIT_REMOTE_AHEAD_SYMBOL$ahead"
		(( behind > 0 )) && GIT_REMOTE_STATE_STR+="$DRAGON__GIT_REMOTE_BEHIND_SYMBOL$behind"
	fi
}

__set_git_status_prefix_and_suffix()
{
	__get_git_remote_state
	__get_git_stash_count
	local state_suffix
	if [[ $VCS_STATUS_HAS_UNSTAGED -eq 1 || $VCS_STATUS_HAS_STAGED -eq 1 || $VCS_STATUS_HAS_UNTRACKED -eq 1 || $VCS_STATUS_HAS_CONFLICTED -eq 1 ]]; then
		state_suffix="$DRAGON__GIT_DIRTY_SUFFIX"
	else
		state_suffix="$DRAGON__GIT_CLEAN_SUFFIX"
	fi
	REAL_DRAGON__GIT_STATUS_PREFIX="$DRAGON__GIT_STATUS_PREFIX$DRAGON__GIT_BRANCH_PREFIX"
	REAL_DRAGON__GIT_STATUS_SUFFIX="$DRAGON__GIT_BRANCH_SUFFIX$GIT_REMOTE_STATE_STR$GIT_STASH_STR${state_suffix}$DRAGON__GIT_STATUS_SUFFIX"
}

dragon__set_git_prompt()
{
	FINAL_GIT_STATUS_CONTENT=""
	! $DRAGON__ENABLE_GIT_STATUS && return
	[[ $VCS_STATUS_RESULT != ok-sync && $VCS_STATUS_RESULT != ok-async ]] && return

	__set_git_status_content
	__set_git_status_color
	__set_git_status_prefix_and_suffix

	__dragon__show "GIT_STATUS"
	FINAL_GIT_STATUS_CONTENT="$_DRAGON_SHOW_RESULT"

	if [[ $DRAGON__GIT_STATUS_ON_NEW_LINE == "never" ]] || ! $DRAGON__ENABLE_MULTILINE; then
		GIT_SHOULD_BE_ON_NEW_LINE=false
	elif [[ $DRAGON__GIT_STATUS_ON_NEW_LINE == "always" ]]; then
		GIT_SHOULD_BE_ON_NEW_LINE=true
	else # "auto"
		__calc_prompt_length
		if (( COLUMNS >= $FINAL_ONE_LINE_LPROMPT_LEN )); then
			GIT_SHOULD_BE_ON_NEW_LINE=false
		else
			GIT_SHOULD_BE_ON_NEW_LINE=true
		fi
	fi
}
