# Override default username colors when over SSH. Called AFTER
# __dragon_copy_defaults USERNAME, so the non-SSH branch is implicit (the
# defaults are already in place).
__set_username_color_via_ssh()
{
	$DRAGON__ENABLE_USERNAME_COLORING_VIA_SSH || return
	__is_via_ssh || return
	REAL_DRAGON__USERNAME_FOREGROUND_COLOR="$DRAGON__USERNAME_VIA_SSH_FOREGROUND_COLOR"
	REAL_DRAGON__USERNAME_BACKGROUND_COLOR="$DRAGON__USERNAME_VIA_SSH_BACKGROUND_COLOR"
	REAL_DRAGON__USERNAME_BOLD="$DRAGON__USERNAME_VIA_SSH_BOLD"
	REAL_DRAGON__USERNAME_UNDERLINE="$DRAGON__USERNAME_VIA_SSH_UNDERLINE"
}

dragon__set_username()
{
	FINAL_DRAGON__USERNAME_CONTENT=""
	! $DRAGON__ENABLE_USERNAME && return

	REAL_DRAGON__USERNAME_CONTENT="%n"
	__dragon_copy_defaults USERNAME
	__set_username_color_via_ssh
	__dragon_finalize USERNAME
}

# Same idiom as username — override colors when SSH.
__set_hostname_color_via_ssh()
{
	$DRAGON__ENABLE_HOSTNAME_COLORING_VIA_SSH || return
	__is_via_ssh || return
	REAL_DRAGON__HOSTNAME_FOREGROUND_COLOR="$DRAGON__HOSTNAME_VIA_SSH_FOREGROUND_COLOR"
	REAL_DRAGON__HOSTNAME_BACKGROUND_COLOR="$DRAGON__HOSTNAME_VIA_SSH_BACKGROUND_COLOR"
	REAL_DRAGON__HOSTNAME_BOLD="$DRAGON__HOSTNAME_VIA_SSH_BOLD"
	REAL_DRAGON__HOSTNAME_UNDERLINE="$DRAGON__HOSTNAME_VIA_SSH_UNDERLINE"
}

dragon__set_hostname()
{
	FINAL_DRAGON__HOSTNAME_CONTENT=""
	! $DRAGON__ENABLE_HOSTNAME && return

	REAL_DRAGON__HOSTNAME_CONTENT="%m"
	__dragon_copy_defaults HOSTNAME
	__set_hostname_color_via_ssh
	__dragon_finalize HOSTNAME
}

__set_directory_content()
{
	REAL_DRAGON__DIRECTORY_CONTENT="%~"
	if [[ $DRAGON__DIRECTORY_FORMAT == "short" ]]; then
		REAL_DRAGON__DIRECTORY_CONTENT="%1~"
	elif [[ $DRAGON__DIRECTORY_FORMAT == "full" ]]; then
		REAL_DRAGON__DIRECTORY_CONTENT="%d"
	fi
}

dragon__set_directory()
{
	FINAL_DRAGON__DIRECTORY_CONTENT=""
	! $DRAGON__ENABLE_DIRECTORY && return

	__set_directory_content
	__dragon_copy_defaults DIRECTORY
	__dragon_finalize DIRECTORY
}

__set_prompt_char_content()
{
	REAL_DRAGON__PROMPT_CHAR_CONTENT="${DRAGON__PROMPT_CHAR//\%/%%}"
	if [[ $VCS_STATUS_RESULT == "ok-sync" || $VCS_STATUS_RESULT == "ok-async" ]]; then
		[[ -z $DRAGON__GIT_PROMPT_CHAR ]] && return
		REAL_DRAGON__PROMPT_CHAR_CONTENT="${DRAGON__GIT_PROMPT_CHAR//\%/%%}"
	fi
}

# prompt_char uses DRAGON__PROMPT_CHAR_DEFAULT_*/_SUCCESS_*/_FAILURE_* colors,
# not the plain DRAGON__PROMPT_CHAR_* set. __dragon_copy_defaults wouldn't
# find the right source vars, so colors are set here explicitly.
__set_prompt_char_color()
{
	REAL_DRAGON__PROMPT_CHAR_FOREGROUND_COLOR="$DRAGON__PROMPT_CHAR_DEFAULT_FOREGROUND_COLOR"
	REAL_DRAGON__PROMPT_CHAR_BACKGROUND_COLOR="$DRAGON__PROMPT_CHAR_DEFAULT_BACKGROUND_COLOR"
	REAL_DRAGON__PROMPT_CHAR_BOLD="$DRAGON__PROMPT_CHAR_DEFAULT_BOLD"
	REAL_DRAGON__PROMPT_CHAR_UNDERLINE="$DRAGON__PROMPT_CHAR_DEFAULT_UNDERLINE"

	if $DRAGON__ENABLE_EXIT_STATUS_PROMPT_COLORING; then
		if (( _DRAGON_EXIT_CODE == 0 )); then
			REAL_DRAGON__PROMPT_CHAR_FOREGROUND_COLOR="$DRAGON__PROMPT_CHAR_SUCCESS_FOREGROUND_COLOR"
			REAL_DRAGON__PROMPT_CHAR_BACKGROUND_COLOR="$DRAGON__PROMPT_CHAR_SUCCESS_BACKGROUND_COLOR"
			REAL_DRAGON__PROMPT_CHAR_BOLD="$DRAGON__PROMPT_CHAR_SUCCESS_BOLD"
			REAL_DRAGON__PROMPT_CHAR_UNDERLINE="$DRAGON__PROMPT_CHAR_SUCCESS_UNDERLINE"
		else
			REAL_DRAGON__PROMPT_CHAR_FOREGROUND_COLOR="$DRAGON__PROMPT_CHAR_FAILURE_FOREGROUND_COLOR"
			REAL_DRAGON__PROMPT_CHAR_BACKGROUND_COLOR="$DRAGON__PROMPT_CHAR_FAILURE_BACKGROUND_COLOR"
			REAL_DRAGON__PROMPT_CHAR_BOLD="$DRAGON__PROMPT_CHAR_FAILURE_BOLD"
			REAL_DRAGON__PROMPT_CHAR_UNDERLINE="$DRAGON__PROMPT_CHAR_FAILURE_UNDERLINE"
		fi
	fi
}

dragon__set_prompt_char()
{
	FINAL_PROMPT_CHAR_CONTENT=""
	[[ -z $DRAGON__PROMPT_CHAR ]] && return

	__set_prompt_char_content
	# Only PREFIX/SUFFIX are mechanical; colors come from the *_DEFAULT_/SUCCESS_/FAILURE_ sets.
	__dragon_copy_defaults PROMPT_CHAR PREFIX SUFFIX
	__set_prompt_char_color
	__dragon_finalize PROMPT_CHAR FINAL_PROMPT_CHAR_CONTENT
}

dragon__set_ssh_prefix()
{
	FINAL_DRAGON__SSH_PREFIX_CONTENT=""
	! $DRAGON__ENABLE_SSH_PREFIX && return
	[[ -z $DRAGON__SSH_PREFIX ]] && return
	__is_via_ssh || return

	REAL_DRAGON__SSH_PREFIX_CONTENT="${DRAGON__SSH_PREFIX//\%/%%}"
	# Colors come from defaults; prefix/suffix are hardcoded empty (this
	# segment doesn't use the user-configurable ones).
	__dragon_copy_defaults SSH_PREFIX FOREGROUND_COLOR BACKGROUND_COLOR BOLD UNDERLINE
	REAL_DRAGON__SSH_PREFIX_PREFIX=""
	REAL_DRAGON__SSH_PREFIX_SUFFIX=""
	__dragon_finalize SSH_PREFIX
}
