__set_username_color()
{
	REAL_DRAGON__USERNAME_FOREGROUND_COLOR="$DRAGON__USERNAME_FOREGROUND_COLOR"
	REAL_DRAGON__USERNAME_BACKGROUND_COLOR="$DRAGON__USERNAME_BACKGROUND_COLOR"
	REAL_DRAGON__USERNAME_BOLD="$DRAGON__USERNAME_BOLD"
	REAL_DRAGON__USERNAME_UNDERLINE="$DRAGON__USERNAME_UNDERLINE"
	if $DRAGON__ENABLE_USERNAME_COLORING_VIA_SSH && __is_via_ssh; then
		REAL_DRAGON__USERNAME_FOREGROUND_COLOR="$DRAGON__USERNAME_VIA_SSH_FOREGROUND_COLOR"
		REAL_DRAGON__USERNAME_BACKGROUND_COLOR="$DRAGON__USERNAME_VIA_SSH_BACKGROUND_COLOR"
		REAL_DRAGON__USERNAME_BOLD="$DRAGON__USERNAME_VIA_SSH_BOLD"
		REAL_DRAGON__USERNAME_UNDERLINE="$DRAGON__USERNAME_VIA_SSH_UNDERLINE"
	fi
}

dragon__set_username()
{
	FINAL_DRAGON__USERNAME_CONTENT=""
	! $DRAGON__ENABLE_USERNAME && return

	REAL_DRAGON__USERNAME_CONTENT="%n"

	REAL_DRAGON__USERNAME_PREFIX="$DRAGON__USERNAME_PREFIX"
	REAL_DRAGON__USERNAME_SUFFIX="$DRAGON__USERNAME_SUFFIX"

	__set_username_color

	__dragon__show "USERNAME"
	FINAL_DRAGON__USERNAME_CONTENT="$SHOW_RESULT"
}

__set_hostname_color()
{
	REAL_DRAGON__HOSTNAME_FOREGROUND_COLOR="$DRAGON__HOSTNAME_FOREGROUND_COLOR"
	REAL_DRAGON__HOSTNAME_BACKGROUND_COLOR="$DRAGON__HOSTNAME_BACKGROUND_COLOR"
	REAL_DRAGON__HOSTNAME_BOLD="$DRAGON__HOSTNAME_BOLD"
	REAL_DRAGON__HOSTNAME_UNDERLINE="$DRAGON__HOSTNAME_UNDERLINE"
	if $DRAGON__ENABLE_HOSTNAME_COLORING_VIA_SSH && __is_via_ssh; then
		REAL_DRAGON__HOSTNAME_FOREGROUND_COLOR="$DRAGON__HOSTNAME_VIA_SSH_FOREGROUND_COLOR"
		REAL_DRAGON__HOSTNAME_BACKGROUND_COLOR="$DRAGON__HOSTNAME_VIA_SSH_BACKGROUND_COLOR"
		REAL_DRAGON__HOSTNAME_BOLD="$DRAGON__HOSTNAME_VIA_SSH_BOLD"
		REAL_DRAGON__HOSTNAME_UNDERLINE="$DRAGON__HOSTNAME_VIA_SSH_UNDERLINE"
	fi
}

dragon__set_hostname()
{
	FINAL_DRAGON__HOSTNAME_CONTENT=""
	! $DRAGON__ENABLE_HOSTNAME && return

	REAL_DRAGON__HOSTNAME_CONTENT="%m"

	REAL_DRAGON__HOSTNAME_PREFIX="$DRAGON__HOSTNAME_PREFIX"
	REAL_DRAGON__HOSTNAME_SUFFIX="$DRAGON__HOSTNAME_SUFFIX"

	__set_hostname_color

	__dragon__show "HOSTNAME"
	FINAL_DRAGON__HOSTNAME_CONTENT="$SHOW_RESULT"
}

__set_directory_content()
{
	REAL_DRAGON__DIRECTORY_CONTENT="%~"
	if [[ $DRAGON__DIRECTORY_FORMAT == "short" ]]; then
		REAL_DRAGON__DIRECTORY_CONTENT="%1~"
	elif [[ $DRAGON__DIRECTORY_FORMAT == "full" ]]; then
		REAL_DRAGON__DIRECTORY_CONTENT="%d"
	fi
}

dragon__set_directory()
{
	FINAL_DRAGON__DIRECTORY_CONTENT=""
	! $DRAGON__ENABLE_DIRECTORY && return

	__set_directory_content

	REAL_DRAGON__DIRECTORY_PREFIX="$DRAGON__DIRECTORY_PREFIX"
	REAL_DRAGON__DIRECTORY_SUFFIX="$DRAGON__DIRECTORY_SUFFIX"

	REAL_DRAGON__DIRECTORY_FOREGROUND_COLOR="$DRAGON__DIRECTORY_FOREGROUND_COLOR"
	REAL_DRAGON__DIRECTORY_BACKGROUND_COLOR="$DRAGON__DIRECTORY_BACKGROUND_COLOR"
	REAL_DRAGON__DIRECTORY_BOLD="$DRAGON__DIRECTORY_BOLD"
	REAL_DRAGON__DIRECTORY_UNDERLINE="$DRAGON__DIRECTORY_UNDERLINE"

	__dragon__show "DIRECTORY"
	FINAL_DRAGON__DIRECTORY_CONTENT="$SHOW_RESULT"
}

__set_prompt_char_content()
{
	REAL_DRAGON__PROMPT_CHAR_CONTENT="$DRAGON__PROMPT_CHAR"
	if [[ $VCS_STATUS_RESULT == "ok-sync" ]]; then
		[[ -z $DRAGON__GIT_PROMPT_CHAR ]] && return
		REAL_DRAGON__PROMPT_CHAR_CONTENT="$DRAGON__GIT_PROMPT_CHAR"
	fi
}

__set_prompt_char_color()
{
	REAL_DRAGON__PROMPT_CHAR_FOREGROUND_COLOR="$DRAGON__PROMPT_CHAR_DEFAULT_FOREGROUND_COLOR"
	REAL_DRAGON__PROMPT_CHAR_BACKGROUND_COLOR="$DRAGON__PROMPT_CHAR_DEFAULT_BACKGROUND_COLOR"
	REAL_DRAGON__PROMPT_CHAR_BOLD="$DRAGON__PROMPT_CHAR_DEFAULT_BOLD"
	REAL_DRAGON__PROMPT_CHAR_UNDERLINE="$DRAGON__PROMPT_CHAR_DEFAULT_UNDERLINE"

	if $DRAGON__ENABLE_EXIT_STATUS_PROMPT_COLORING; then
		if [[ "$_DRAGON_EXIT_CODE" -eq 0 ]]; then
			REAL_DRAGON__PROMPT_CHAR_FOREGROUND_COLOR="$DRAGON__PROMPT_CHAR_SUCCESS_FOREGROUND_COLOR"
			REAL_DRAGON__PROMPT_CHAR_BACKGROUND_COLOR="$DRAGON__PROMPT_CHAR_SUCCESS_BACKGROUND_COLOR"
			REAL_DRAGON__PROMPT_CHAR_BOLD="$DRAGON__PROMPT_CHAR_SUCCESS_BOLD"
			REAL_DRAGON__PROMPT_CHAR_UNDERLINE="$DRAGON__PROMPT_CHAR_SUCCESS_UNDERLINE"
		else
			REAL_DRAGON__PROMPT_CHAR_FOREGROUND_COLOR="$DRAGON__PROMPT_CHAR_FAILURE_FOREGROUND_COLOR"
			REAL_DRAGON__PROMPT_CHAR_BACKGROUND_COLOR="$DRAGON__PROMPT_CHAR_FAILURE_BACKGROUND_COLOR"
			REAL_DRAGON__PROMPT_CHAR_BOLD="$DRAGON__PROMPT_CHAR_FAILURE_BOLD"
			REAL_DRAGON__PROMPT_CHAR_UNDERLINE="$DRAGON__PROMPT_CHAR_FAILURE_UNDERLINE"
		fi
	fi
}

dragon__set_prompt_char()
{
	FINAL_PROMPT_CHAR_CONTENT=""
	[[ -z $DRAGON__PROMPT_CHAR ]] && return

	__set_prompt_char_content

	REAL_DRAGON__PROMPT_CHAR_PREFIX="$DRAGON__PROMPT_CHAR_PREFIX"
	REAL_DRAGON__PROMPT_CHAR_SUFFIX="$DRAGON__PROMPT_CHAR_SUFFIX"

	__set_prompt_char_color

	__dragon__show "PROMPT_CHAR"
	FINAL_PROMPT_CHAR_CONTENT="$SHOW_RESULT"
}

dragon__set_ssh_prefix()
{
	FINAL_DRAGON__SSH_PREFIX_CONTENT=""
	! $DRAGON__ENABLE_SSH_PREFIX && return
	[[ -z $DRAGON__SSH_PREFIX ]] && return
	__is_via_ssh || return

	REAL_DRAGON__SSH_PREFIX_CONTENT="$DRAGON__SSH_PREFIX"

	REAL_DRAGON__SSH_PREFIX_PREFIX=""
	REAL_DRAGON__SSH_PREFIX_SUFFIX=""

	REAL_DRAGON__SSH_PREFIX_FOREGROUND_COLOR="$DRAGON__SSH_PREFIX_FOREGROUND_COLOR"
	REAL_DRAGON__SSH_PREFIX_BACKGROUND_COLOR="$DRAGON__SSH_PREFIX_BACKGROUND_COLOR"
	REAL_DRAGON__SSH_PREFIX_BOLD="$DRAGON__SSH_PREFIX_BOLD"
	REAL_DRAGON__SSH_PREFIX_UNDERLINE="$DRAGON__SSH_PREFIX_UNDERLINE"

	__dragon__show "SSH_PREFIX"
	FINAL_DRAGON__SSH_PREFIX_CONTENT="$SHOW_RESULT"
}
