#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# lan_scan.sh - Scan the LAN for hostnames, write per-host ssh aliases.
#
# Run by the daily cron installed via `master-oogway lan-ssh setup`, or by hand
# via `master-oogway lan-ssh refresh`. Resolves every IP in the subnet to a
# hostname (parallel reverse-DNS) and writes an alias file that is auto-sourced
# by the custom-zsh/ seam in zshrc.master-oogway on the next shell start.
#
# This file IS the config file: edit the vars below to tune subnet, ssh user,
# and ssh flags. SSH_FLAGS is baked into each alias when written.
# ------------------------------------------------------------------------------
set -Eeuo pipefail

# -- Config (edit these) -------------------------------------------------------

# Subnet in CIDR. Empty = auto-detect from the default route.
SUBNET="${MO_LAN_SUBNET:-}"

# User baked into each alias. Empty = keep literal $USER (resolved at ssh time).
SSH_USER="${MO_LAN_SSH_USER:-}"

# Flags baked into each alias, between `ssh` and the target.
SSH_FLAGS="${MO_LAN_SSH_FLAGS:--o StrictHostKeyChecking=accept-new}"

# -- Paths ---------------------------------------------------------------------

MO_CONFIG_DIR="${MO_CONFIG_DIR:-$HOME/.config/master-oogway}"
readonly ALIAS_FILE="${MO_CONFIG_DIR}/custom-zsh/lan-hosts.zsh"

# -- Subnet detection ----------------------------------------------------------

detect_subnet() {
	[[ -n "$SUBNET" ]] && { echo "$SUBNET"; return; }
	local iface
	iface=$(ip route show default 2>/dev/null | awk '/default/ { print $5; exit }')
	[[ -z "$iface" ]] && return 1
	ip -o -f inet addr show "$iface" 2>/dev/null | awk '{ print $4; exit }'
}

# -- Discovery -----------------------------------------------------------------
# nmap -sL is a pure list scan: parallel reverse-DNS over the range, no probe,
# no root. Fastest path to "hostnames on the subnet". Falls back to a parallel
# dig loop when nmap is absent.

scan_nmap() {
	nmap -sL "$1" 2>/dev/null \
		| awk '/Nmap scan report for/ && /\(/ { print $5 }'
}

scan_dig() {
	# ponytail: /24 only. Wider ranges need nmap; add CIDR expansion if a
	# non-/24 LAN ever shows up here.
	local base="${1%/*}" prefix="${1#*/}"
	[[ "$prefix" == "24" ]] || { echo "lan_scan: dig fallback only handles /24 (got /$prefix)" >&2; return 1; }
	local net="${base%.*}"
	seq 1 254 | xargs -P 64 -I{} sh -c \
		'dig +short +time=1 +tries=1 -x '"$net"'.{} 2>/dev/null | sed "s/\.$//" | head -1' \
		2>/dev/null
}

discover() {
	local subnet="$1"
	if command -v nmap &>/dev/null; then
		scan_nmap "$subnet"
	elif command -v dig &>/dev/null; then
		scan_dig "$subnet"
	else
		echo "lan_scan: need nmap or dig (sudo apt install nmap)" >&2
		return 1
	fi
}

# -- Filter — keep short, valid, non-local hostnames ---------------------------

filter_names() {
	local me name
	me=$(hostname -s 2>/dev/null || hostname)
	awk -F. 'NF { print $1 }' \
		| grep -E '^[A-Za-z0-9_-]+$' \
		| grep -vixF "$me" \
		| sort -u \
		| while read -r name; do
			# A LAN host controls its own reverse-DNS name, so a hostile host
			# could name itself `ls`/`sudo`/`git` and the generated alias would
			# shadow that command. Drop any name that collides with an existing
			# command (PATH binary, builtin, alias, function).
			command -v "$name" &>/dev/null && continue
			echo "$name"
		done
}

# -- Alias file ----------------------------------------------------------------

render_aliases() {
	local user_prefix
	if [[ -n "$SSH_USER" ]]; then
		user_prefix="${SSH_USER}@"
	else
		# shellcheck disable=SC2016  # literal $USER: resolves in the user's shell at ssh time
		user_prefix='$USER@'
	fi
	echo "# autogenerated by mo-cli lan_scan.sh — do not edit by hand"
	echo "# Refreshed: $(date -Iseconds 2>/dev/null || date)"
	local host
	while read -r host; do
		[[ -z "$host" ]] && continue
		printf "alias %s='ssh %s %s%s'\n" "$host" "$SSH_FLAGS" "$user_prefix" "$host"
	done
}

main() {
	local subnet
	subnet=$(detect_subnet) || { echo "lan_scan: could not detect subnet" >&2; exit 1; }

	local hosts
	hosts=$(discover "$subnet" | filter_names) || true
	[[ -z "$hosts" ]] && { echo "lan_scan: no hosts found on $subnet" >&2; exit 1; }

	local new
	new=$(printf '%s\n' "$hosts" | render_aliases)

	mkdir -p "${ALIAS_FILE%/*}"
	# Skip the write when only the timestamp would change, so a running shell's
	# next source is a no-op and steady-state cost stays zero.
	if [[ -f "$ALIAS_FILE" ]] && diff -q \
		<(grep -v '^# Refreshed:' "$ALIAS_FILE") \
		<(printf '%s\n' "$new" | grep -v '^# Refreshed:') &>/dev/null; then
		exit 0
	fi
	local tmp
	tmp=$(mktemp "${ALIAS_FILE}.XXXXXX")
	printf '%s\n' "$new" > "$tmp"
	mv "$tmp" "$ALIAS_FILE"
	echo "lan_scan: wrote $(printf '%s\n' "$hosts" | grep -c .) host aliases to $ALIAS_FILE"
}

main "$@"
