#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# lan_scan.sh - Scan the LAN for hostnames, write per-host ssh aliases.
#
# Run by the daily cron installed via `master-oogway lan-ssh setup`, or by hand
# via `master-oogway lan-ssh refresh`. Calls scan_hosts.py (reverse-DNS over the
# configured subnets) and writes an alias file that is auto-sourced by the
# custom-zsh/ seam in zshrc.master-oogway on the next shell start.
#
# Pass --list to print discovered hostnames instead of writing the alias file.
#
# This file IS the config file: edit the vars below to tune ssh user and ssh
# flags. SSH_FLAGS is baked into each alias when written. Subnets are
# configured separately — see MO_LAN_SUBNETS in scan_hosts.py.
# ------------------------------------------------------------------------------
set -Eeuo pipefail

# -- Config (edit these) -------------------------------------------------------

# User baked into each alias. Empty = keep literal $USER (resolved at ssh time).
SSH_USER="${MO_LAN_SSH_USER:-}"

# Flags baked into each alias, between `ssh` and the target.
SSH_FLAGS="${MO_LAN_SSH_FLAGS:--o StrictHostKeyChecking=accept-new}"

# -- Paths ---------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCAN_PY="${SCRIPT_DIR}/scan_hosts.py"

MO_CONFIG_DIR="${MO_CONFIG_DIR:-$HOME/.config/master-oogway}"
readonly ALIAS_FILE="${MO_CONFIG_DIR}/custom-zsh/lan-hosts.zsh"

# -- Discovery -----------------------------------------------------------------
# scan_hosts.py does reverse-DNS via gethostbyaddr, first-dot-segment stripping,
# regex validation, and dedup. Prints one bare hostname per line on stdout.

discover() {
	command -v python3 &>/dev/null || {
		# This is a standalone bash script run by cron — it cannot source the
		# zsh lib/platform.zsh, so it can't reach _mo_is_macos or _mo_pkg_hint.
		# platform-lint: allow
		if [[ "$(uname -s)" == Darwin ]]; then
			echo "lan_scan: need python3 (brew install python3)" >&2
		else
			# platform-lint: allow — see above
			echo "lan_scan: need python3 (sudo apt install python3)" >&2
		fi
		return 1
	}
	python3 "$SCAN_PY"
}

# -- Filter — drop names colliding with existing commands ----------------------
# A LAN host controls its own reverse-DNS name, so a hostile host could name
# itself `ls`/`sudo`/`git` and the generated alias would shadow that command.
# scan_hosts.py already validated + deduped; this pass only does the shell-side
# collision check (needs `command -v`).

filter_names() {
	local name
	while read -r name; do
		[[ -z "$name" ]] && continue
		command -v "$name" &>/dev/null && continue
		echo "$name"
	done
}

# -- Alias file ----------------------------------------------------------------

render_aliases() {
	# SSH_FLAGS/SSH_USER are user config interpolated into a single-quoted alias
	# body that gets auto-sourced on every shell start, so a single quote in
	# either would close the quoting and execute the remainder. %q emits a
	# shell-safe token; the flags still word-split into separate ssh arguments.
	local flags_q user_q
	printf -v flags_q '%q' "$SSH_FLAGS"
	if [[ -n "$SSH_USER" ]]; then
		printf -v user_q '%q@' "$SSH_USER"
	else
		# shellcheck disable=SC2016  # literal $USER: resolves in the user's shell at ssh time
		user_q='$USER@'
	fi
	echo "# autogenerated by mo-cli lan_scan.sh — do not edit by hand"
	echo "# Refreshed: $(date -Iseconds 2>/dev/null || date)"
	local host
	while read -r host; do
		[[ -z "$host" ]] && continue
		printf "alias %s='ssh '%s' '%s%s''\n" "$host" "$flags_q" "$user_q" "$host"
	done
}

main() {
	local list_only=false
	case "${1:-}" in
		--list) list_only=true ;;
		-h|--help)
			echo "Usage: lan_scan.sh [--list]"
			echo "  Reverse-resolve the configured LAN subnets and write host aliases."
			echo "  --list  print discovered hostnames only; skip the alias-file write."
			exit 0
			;;
	esac

	local hosts status=0
	hosts=$(discover | filter_names) || status=$?
	if (( status != 0 )); then
		echo "lan_scan: discovery failed (see error above) — check python3 and DNS" >&2
		exit 1
	fi
	if [[ -z "$hosts" ]]; then
		if $list_only; then
			exit 0
		fi
		echo "lan_scan: no hosts found" >&2
		exit 1
	fi

	if $list_only; then
		printf '%s\n' "$hosts"
		exit 0
	fi

	local new
	new=$(printf '%s\n' "$hosts" | render_aliases)

	mkdir -p "${ALIAS_FILE%/*}"
	# Skip the write when only the timestamp would change, so a running shell's
	# next source is a no-op and steady-state cost stays zero.
	if [[ -f "$ALIAS_FILE" ]] && diff -q \
		<(grep -v '^# Refreshed:' "$ALIAS_FILE") \
		<(printf '%s\n' "$new" | grep -v '^# Refreshed:') &>/dev/null; then
		exit 0
	fi
	local tmp
	tmp=$(mktemp "${ALIAS_FILE}.XXXXXX")
	printf '%s\n' "$new" > "$tmp"
	mv "$tmp" "$ALIAS_FILE"
	echo "lan_scan: wrote $(printf '%s\n' "$hosts" | grep -c .) host aliases to $ALIAS_FILE"
}

main "$@"
