# dragon preset: boxed
# Multiline ╭/│/╰╴ border, git on new line, ⏱ timer. Pair with any palette.
export DRAGON__USER_HOST_SEPARATOR=' at '
export DRAGON__HOST_DIR_SEPARATOR=' in '
export DRAGON__ENABLE_MULTILINE='true'
export DRAGON__FIRST_LINE_SEPARATOR_CHAR='╭ '
export DRAGON__NEW_LINE_SEPARATOR_CHAR='│'
export DRAGON__LAST_LINE_SEPARATOR_CHAR='╰╴'
export DRAGON__GIT_STATUS_ON_NEW_LINE='auto'
export DRAGON__GIT_STATUS_PREFIX=' on '
export DRAGON__GIT_BRANCH_PREFIX='‹'
export DRAGON__GIT_BRANCH_SUFFIX='›'
export DRAGON__GIT_CLEAN_SUFFIX=' ✔'
export DRAGON__GIT_DIRTY_SUFFIX=' ✘'
export DRAGON__PROMPT_CHAR='❯'
export DRAGON__ENABLE_DATE_TIME='true'
export DRAGON__DATE_TIME_PREFIX=' '
export DRAGON__ENABLE_EXEC_TIMER='true'
export DRAGON__EXEC_TIMER_PREFIX=' ⏱ '
export DRAGON__EXEC_TIMER_SUFFIX=''
export DRAGON__EXEC_TIMER_THRESHOLD='3'
export DRAGON__ENABLE_EXIT_STATUS='true'
