# dragon preset: verbose
# Maximum info. Multiline, full paths, timestamps, rich git.
export DRAGON__DIRECTORY_FORMAT='full'
export DRAGON__USER_HOST_SEPARATOR=' at '
export DRAGON__HOST_DIR_SEPARATOR=' in '
export DRAGON__FIRST_LINE_SEPARATOR_CHAR='╭ '
export DRAGON__NEW_LINE_SEPARATOR_CHAR='│'
export DRAGON__LAST_LINE_SEPARATOR_CHAR='╰╴'
export DRAGON__ENABLE_MULTILINE='true'
export DRAGON__GIT_STATUS_ON_NEW_LINE='always'
export DRAGON__GIT_STATUS_PREFIX=' on '
export DRAGON__GIT_BRANCH_PREFIX='‹'
export DRAGON__GIT_BRANCH_SUFFIX='›'
export DRAGON__GIT_CLEAN_SUFFIX='✔'
export DRAGON__GIT_DIRTY_SUFFIX='✘'
export DRAGON__ENABLE_DATE_TIME='true'
export DRAGON__DATE_TIME_FORMAT='%D{%d/%m/%y | %H:%M:%S}'
export DRAGON__DATE_TIME_PREFIX=' at '
export DRAGON__ENABLE_EXEC_TIMER='true'
export DRAGON__EXEC_TIMER_PREFIX=' took '
export DRAGON__EXEC_TIMER_THRESHOLD='2'
export DRAGON__ENABLE_JOB_COUNT='true'
export DRAGON__JOB_COUNT_SUFFIX=' jobs '
export DRAGON__ENABLE_EXIT_STATUS='true'
export DRAGON__EXIT_STATUS_PREFIX=' code:'
