# configure/writer.zsh — conf file generator

# $1 (optional): the preset this config is based on. Written as a
# `# preset: <name>` header so the picker can preselect it and the on-update
# regen knows the base — this is the sole source of truth for the active preset.
_dragon_write_conf() {
	local preset="${1:-}"
	local tmp_file="${_DRAGON_CONF_FILE}.wizard.tmp"
	# base64 is required: the SSH-forwarding payload (baked below) has no
	# fallback encoder. Fail loudly here — this runs from dragon-configure /
	# install, an interactive setup path where an error is actionable.
	if ! command -v base64 &>/dev/null; then
		print -P "%F{red}[dragon]%f base64 not found — install coreutils, then re-run dragon-configure." >&2
		return 1
	fi
	# Guarantee cleanup of the tmp file on any exit path — including a failed
	# mv (read-only filesystem, ENOSPC, etc.). Cleared to `trap - EXIT` on
	# success so it doesn't fire after the mv completes.
	trap 'rm -f "${tmp_file}"' EXIT

	{
		[[ -n "$preset" ]] && printf '# preset: %s\n' "$preset"
		cat <<'HEADER'
##########################################
#### Theme configuration: dragon #####
##########################################
# Generated by dragon-configure. Edit freely, or re-run it to reconfigure.
# Uncommented lines (export ...) override theme defaults.
# Commented-out lines (# export ...) show all available options at their defaults.
#
# SSH forwarding: 'master-oogway lan-ssh setup' adds SendEnv DRAGON__PAYLOAD to
# ~/.ssh/config so your theme travels to remote machines running dragon. This
# file bakes all settings into the single DRAGON__PAYLOAD var at the bottom;
# the remote's dragon.zsh decodes it. Forwarding one packed var (not ~130
# separate ones) stays under sshd's per-session AcceptEnv limit.
#
# Variable naming convention:
#   DRAGON__ENABLE_{FEATURE}           — bool: true / false
#   DRAGON__{FEATURE}_FOREGROUND_COLOR — color name or 0-255
#   DRAGON__{FEATURE}_BACKGROUND_COLOR — color name or 0-255, empty = no color
#   DRAGON__{FEATURE}_BOLD             — bool
#   DRAGON__{FEATURE}_UNDERLINE        — bool
#   DRAGON__{FEATURE}_PREFIX           — string prepended before the segment
#   DRAGON__{FEATURE}_SUFFIX           — string appended after the segment
#
# Color values: name (black red green yellow blue magenta cyan white
#   grey maroon lime olive navy fuchsia aqua silver) or numeric 0-255.
# To browse 256-color palette, run:
#   for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done

HEADER

		# Write each group
		local group title pad_len dashes vars var val default hint vtype q=\' safe_val
		for group in "${_DRAGON_GROUPS[@]}"; do
			title="${_DRAGON_GROUP_TITLE[$group]}"
			pad_len=$(( 76 - 4 - ${#title} - 1 ))
			(( pad_len < 2 )) && pad_len=2
			dashes="${(r:$pad_len::─:):-}"
			printf '# ── %s %s\n' "$title" "$dashes"
			printf '# %s\n' "${_DRAGON_GROUP_DESC[$group]}"

			vars=( ${(s: :)_DRAGON_GROUP_VARS[$group]} )
			for var in "${vars[@]}"; do
				val="${_DRAGON_CURRENT[$var]}"
				default="${_DRAGON_DEFAULTS[$var]:-}"
				hint="${_DRAGON_HINT[$var]:-}"
				vtype="${_DRAGON_TYPE[$var]:-string}"
				# Single-quoted output: immune to shell expansion of $, `, and \.
				# The only char needing escape inside '...' is ' itself, via the
				# standard '\'' idiom (close-quote, escaped-quote, reopen-quote).
				# q/safe_val declared above the loops to avoid zsh local-in-loop
				# re-declaration bug that leaks array values to the redirect fd.
				safe_val="${val//$q/$q\\$q$q}"

				# Emit type hint for special vars
				if [[ -n "$hint" ]]; then
					printf '# %s\n' "$hint"
				elif [[ "$vtype" == enum:* ]]; then
					printf '# Values: %s\n' "${vtype#enum:}"
				fi

				if [[ "$val" == "$default" ]]; then
					printf "# export DRAGON__%s='%s'  # default\n" "$var" "$safe_val"
				else
					printf "export DRAGON__%s='%s'\n" "$var" "$safe_val"
				fi
			done
			printf '\n'
		done

		# Bake ALL resolved values into one base64 var so SSH forwarding ships a
		# single DRAGON__PAYLOAD (see header). Iterate every schema key, not the
		# grouped emit above — some vars (e.g. USE_NERD_FONT) belong to no editor
		# group but must still forward. `:=` keeps a payload already forwarded
		# from an upstream hop, so it survives A→B→C chains.
		local -a payload_lines
		local pk pv
		for pk in "${(@k)_DRAGON_CURRENT}"; do
			pv="${_DRAGON_CURRENT[$pk]//$q/$q\\$q$q}"
			payload_lines+=( "export DRAGON__${pk}='${pv}'" )
		done
		local payload
		payload="$(printf '%s\n' "${payload_lines[@]}" | base64 -w0)"
		printf '\n: ${DRAGON__PAYLOAD:=%s}\nexport DRAGON__PAYLOAD\n' "$q$payload$q"
	} > "$tmp_file"

	if ! zsh -n "$tmp_file" 2>/dev/null; then
		print -P "%F{red}[dragon]%f Internal error: generated conf.zsh failed syntax check — not saved." >&2
		return 1
	fi

	if ! command mv "$tmp_file" "${_DRAGON_CONF_FILE}"; then
		print -P "%F{red}[dragon]%f Failed to write ${_DRAGON_CONF_FILE} (disk full?)" >&2
		return 1
	fi
	trap - EXIT
}
