# Provides: per-LAN-host `s-<hostname>` aliases, ssh/scp tab completion, and a
# managed ~/.ssh/config.d/lan-hosts (Port directive for non-22 listeners).
# CLI: mo-lan-ssh list|refresh|status|setup|help.
# Phase 1 — no ssh wrapper yet; key install is manual via ssh-copy-id.
#
# Requires: dig (any one of strat_axfr/nmap/arp-scan/known_hosts for discovery)

# EPOCHSECONDS lives in zsh/datetime; load once so loader paths don't fork date.
zmodload -F zsh/datetime b:EPOCHSECONDS 2>/dev/null

# ── Paths ─────────────────────────────────────────────────────────────────────

typeset -g _MO_LAN_SSH_DIR="${0:a:h}"
typeset -g _MO_LAN_SSH_DISCOVER="${_MO_LAN_SSH_DIR}/_mo_lan_discover.zsh"
typeset -g _MO_LAN_SSH_CACHE="${HOME}/.config/master-oogway/lan-hosts"
typeset -g _MO_LAN_SSH_LOCK="${HOME}/.config/master-oogway/lan-hosts.lock"
typeset -g _MO_LAN_SSH_SHA="${HOME}/.config/master-oogway/lan-hosts.sshconf.sha"
typeset -g _MO_LAN_SSH_OUTPUT="${HOME}/.ssh/config.d/lan-hosts"
typeset -g _MO_LAN_SSH_USER_CONFIG="${HOME}/.ssh/config"
typeset -g _MO_LAN_SSH_USER_CONFIG_DIR="${HOME}/.ssh/config.d"

# ── Defaults (env-var overridable; same names used by _mo_lan_discover.zsh) ──

: ${MO_LAN_TTL:=86400}
: ${MO_LAN_SSH_PORTS:=22}
: ${MO_LAN_PROBE_TIMEOUT:=2}
: ${MO_LAN_PROBE_PARALLEL:=20}
: ${MO_LAN_EXCLUDE:=}
: ${MO_LAN_VERBOSE:=false}

# ── Helpers ───────────────────────────────────────────────────────────────────

_mo_lan_log() {
    [[ "$MO_LAN_VERBOSE" == "true" ]] || return 0
    print -P "%F{245}[mo-lan-ssh]%f $*" >&2
}

_mo_lan_network_id() {
    local gw iface subnet
    gw=$(ip route show default 2>/dev/null | awk '/default/ { print $3; exit }')
    iface=$(ip route show default 2>/dev/null | awk '/default/ { print $5; exit }')
    [[ -z "$iface" ]] && { echo "unknown"; return; }
    subnet=$(ip -o -f inet addr show "$iface" 2>/dev/null | awk '{ print $4 }' | head -1)
    print -- "${gw}-${subnet}" | md5sum | cut -d' ' -f1 | cut -c1-8
}

_mo_lan_cache_age() {
    local mtime
    mtime=$(stat -c %Y "$_MO_LAN_SSH_CACHE" 2>/dev/null) || { echo 999999999; return; }
    echo $(( EPOCHSECONDS - mtime ))
}

_mo_lan_cache_network() {
    [[ -f "$_MO_LAN_SSH_CACHE" ]] || return 1
    grep -m1 '^# Refreshed:' "$_MO_LAN_SSH_CACHE" 2>/dev/null \
        | sed -n 's/.*network=\([a-f0-9]*\).*/\1/p'
}

# Run discovery in background. flock prevents concurrent shells from trampling.
_mo_lan_refresh_async() {
    [[ -f "$_MO_LAN_SSH_DISCOVER" ]] || return
    (
        flock -n 9 || exit 0   # someone else is already refreshing — bail silently
        zsh "$_MO_LAN_SSH_DISCOVER" 2>/dev/null
    ) 9>"$_MO_LAN_SSH_LOCK" &!
}

_mo_lan_check_ttl_async() {
    local age
    age=$(_mo_lan_cache_age)
    if (( age > MO_LAN_TTL )); then
        _mo_lan_log "Cache stale (${age}s > ${MO_LAN_TTL}s) — refreshing in background"
        _mo_lan_refresh_async
    fi
}

_mo_lan_check_network_async() {
    local cur stored
    cur=$(_mo_lan_network_id)
    stored=$(_mo_lan_cache_network)
    if [[ -n "$cur" && -n "$stored" && "$cur" != "$stored" ]]; then
        _mo_lan_log "Network changed (${stored} → ${cur}) — refreshing in background"
        _mo_lan_refresh_async
    fi
}

# Re-render ~/.ssh/config.d/lan-hosts. Skip if cache content hasn't changed
# since last render — checked via sha256 of the cache file. Avoids any disk
# write on the common shell-start path.
_mo_lan_maybe_write_sshconf() {
    [[ -f "$_MO_LAN_SSH_CACHE" ]] || return
    local cache_sha last_sha=""
    cache_sha=$(sha256sum "$_MO_LAN_SSH_CACHE" 2>/dev/null | cut -d' ' -f1)
    [[ -f "$_MO_LAN_SSH_SHA" ]] && last_sha=$(< "$_MO_LAN_SSH_SHA")
    [[ "$cache_sha" == "$last_sha" ]] && return

    mkdir -p "$_MO_LAN_SSH_USER_CONFIG_DIR"
    chmod 700 "$_MO_LAN_SSH_USER_CONFIG_DIR"

    local tmp="${_MO_LAN_SSH_OUTPUT}.tmp"
    {
        echo "# mo-lan-ssh — autogenerated, do not edit by hand"
        echo "# Source of truth: ${_MO_LAN_SSH_CACHE}"
        echo ""
        local line h p
        while IFS= read -r line; do
            [[ "$line" == '#'* || -z "$line" ]] && continue
            if [[ "$line" == *:* ]]; then
                h="${line%%:*}"; p="${line##*:}"
                echo "Host $h"
                echo "    Port $p"
                echo ""
            else
                echo "Host $line"
                echo ""
            fi
        done < "$_MO_LAN_SSH_CACHE"
    } > "$tmp"
    chmod 600 "$tmp"
    mv "$tmp" "$_MO_LAN_SSH_OUTPUT"
    print -- "$cache_sha" > "$_MO_LAN_SSH_SHA"
    _mo_lan_log "Wrote ${_MO_LAN_SSH_OUTPUT}"
}

# ── Loader (runs once at shell startup, no blocking, target <10ms) ────────────

() {
    # First-run case: no cache. Kick off background discovery; this shell has
    # no aliases. Per resolved decision (b): never block shell start.
    if [[ ! -f "$_MO_LAN_SSH_CACHE" ]]; then
        _mo_lan_refresh_async
        return
    fi

    # Background-refresh triggers (don't block this shell either way)
    _mo_lan_check_ttl_async
    _mo_lan_check_network_async

    # Parse cache: hostname or hostname:port per line.
    local -a hosts=()
    local line h
    while IFS= read -r line; do
        [[ "$line" == '#'* || -z "$line" ]] && continue
        if [[ "$line" == *:* ]]; then
            h="${line%%:*}"
        else
            h="$line"
        fi
        hosts+=("$h")
    done < "$_MO_LAN_SSH_CACHE"

    (( ${#hosts[@]} == 0 )) && return

    # 1. s-<host> aliases — `s-` prefix guarantees zero conflict with anything.
    for h in "${hosts[@]}"; do
        alias -- "s-${h}=ssh ${h}"
    done

    # 2. Tab completion for ssh/scp/sftp/rsync via zsh's _hosts source.
    zstyle ':completion:*:(ssh|scp|sftp|rsync):*' hosts "${hosts[@]}"

    # 3. ssh-config write — idempotent, skipped when nothing changed.
    _mo_lan_maybe_write_sshconf

    # 4. SSH wrapper — registered only with a non-empty hostset AND when not
    # explicitly disabled. Defining ssh() conditionally means users without
    # LAN hosts (or with MO_LAN_AUTO_TRUST=false) get the stock ssh binary
    # behavior — `which ssh` will show the file, not our function.
    if [[ "${MO_LAN_AUTO_TRUST:-true}" != "false" ]]; then
        typeset -gA _MO_LAN_HOSTSET=()
        for h in "${hosts[@]}"; do _MO_LAN_HOSTSET[$h]=1; done
        ssh() { _mo_lan_ssh_wrapper "$@"; }
    fi
}

# ── SSH wrapper (Phase 2) ─────────────────────────────────────────────────────
#
# Wraps the `ssh` command, but only for hosts in the LAN cache. For every
# other target (github.com, work servers, IP literals not in cache) the
# wrapper does ONE associative-array lookup then falls through to
# `command ssh` with zero added latency.
#
# What it does for LAN targets (and only for them):
#   1. Probe with BatchMode=yes — does pubkey auth work in ≤ probe_timeout?
#      - Yes  → just ssh.
#      - "Host key verification failed" / "REMOTE HOST IDENTIFICATION HAS
#         CHANGED" → ssh-keygen -R the host (we trust LAN key changes),
#         then re-probe. If now OK → just ssh.
#      - Permission denied / no working key → ssh-copy-id interactively,
#        then ssh.
#
# Safety gates (any one of these → pass through to bare ssh, no surprise):
#   - The target hostname isn't in _MO_LAN_HOSTSET.
#   - MO_LAN_AUTO_TRUST=false.
#   - Stdin isn't a TTY (script-pipe usage like `cmd | ssh foo ...`).

# Parse ssh argv to find the destination (first non-flag arg, skipping the
# values of option-taking flags). Returns empty string if no target found.
_mo_lan_extract_target() {
    local arg next_is_value=false
    for arg in "$@"; do
        if $next_is_value; then
            next_is_value=false
            continue
        fi
        case "$arg" in
            # Flags taking a separate-arg value (-l user / -p 2222 / -i key / etc.)
            -[BbcDEeFIiJLlmOoPpRSWwQ])
                next_is_value=true
                ;;
            # Flags with attached value (-p2222), or any other -flag (-v, -A, …)
            -*)
                ;;
            # First non-flag arg is the destination
            *)
                print -- "$arg"
                return
                ;;
        esac
    done
}

_mo_lan_ssh_wrapper() {
    # Non-interactive stdin (pipe/script) → don't interfere with the user's flow
    [[ -t 0 ]] || { command ssh "$@"; return; }

    # MO_LAN_AUTO_TRUST=false → wrapper disabled, pass through
    [[ "${MO_LAN_AUTO_TRUST:-true}" == "false" ]] && { command ssh "$@"; return; }

    local target target_host
    target=$(_mo_lan_extract_target "$@")
    target_host="${target##*@}"   # strip user@ if present

    # Not a LAN host → pass through with zero ceremony
    if [[ -z "$target_host" || -z "${_MO_LAN_HOSTSET[$target_host]:-}" ]]; then
        command ssh "$@"
        return
    fi

    # Probe: BatchMode rejects password auth, so we only succeed on a working
    # key. accept-new auto-records a first-time host key but rejects changes.
    local probe_err probe_rc
    probe_err=$(command ssh -o BatchMode=yes \
                            -o ConnectTimeout="$MO_LAN_PROBE_TIMEOUT" \
                            -o StrictHostKeyChecking=accept-new \
                            "$target" true 2>&1)
    probe_rc=$?

    if (( probe_rc == 0 )); then
        # Key auth works — just ssh.
        command ssh "$@"
        return
    fi

    # Key mismatch? Trust the LAN, purge, re-probe. Stock ssh's normal
    # MITM defense is exactly what we're relaxing here, see README.
    if [[ "$probe_err" == *"REMOTE HOST IDENTIFICATION HAS CHANGED"* \
       || "$probe_err" == *"Host key verification failed"* ]]; then
        print -P "%F{yellow}[mo-lan-ssh]%f Host key changed for $target_host — purging old key (LAN host: trusted)"
        ssh-keygen -R "$target_host" >/dev/null 2>&1
        probe_err=$(command ssh -o BatchMode=yes \
                                -o ConnectTimeout="$MO_LAN_PROBE_TIMEOUT" \
                                -o StrictHostKeyChecking=accept-new \
                                "$target" true 2>&1)
        probe_rc=$?
        if (( probe_rc == 0 )); then
            command ssh "$@"
            return
        fi
    fi

    # Classify the failure. Only run ssh-copy-id when password (or
    # keyboard-interactive) auth is actually offered — copying a key
    # accomplishes nothing if the failure is "connection refused", a
    # KEX mismatch with an ancient device, network unreachable, etc.
    if [[ "$probe_err" == *"Permission denied"* \
       && ( "$probe_err" == *"password"* || "$probe_err" == *"keyboard-interactive"* ) ]]; then
        print -P "%F{cyan}[mo-lan-ssh]%f No working key for $target_host — running ssh-copy-id"
        if command ssh-copy-id "$target" </dev/tty; then
            print -P "%F{green}[mo-lan-ssh]%f Key installed; reconnecting…"
        else
            print -P "%F{yellow}[mo-lan-ssh]%f ssh-copy-id failed — falling through to interactive ssh"
        fi
    elif [[ "$probe_err" == *"Permission denied"* ]]; then
        # Pubkey-only server and our keys aren't authorized. ssh-copy-id
        # has no way to bootstrap. Tell the user the manual path.
        print -P "%F{yellow}[mo-lan-ssh]%f $target_host accepts only pubkey auth; bootstrap manually:" >&2
        print -P "%F{245}  ssh-copy-id -f -i ~/.ssh/<your-key.pub> $target%f" >&2
    fi
    # Network errors / protocol mismatch / etc. — say nothing, just let the
    # real ssh emit the actual error to the user.
    command ssh "$@"
}

# ── CLI dispatcher ────────────────────────────────────────────────────────────

_mo_lan_status() {
    if [[ ! -f "$_MO_LAN_SSH_CACHE" ]]; then
        print -P "%F{yellow}No cache yet.%f Run: %Bmo-lan-ssh refresh%b"
        return
    fi
    local age hours mins refreshed count cur_net cache_net net_status
    age=$(_mo_lan_cache_age)
    hours=$(( age / 3600 ))
    mins=$(( (age % 3600) / 60 ))
    refreshed=$(grep -m1 '^# Refreshed:' "$_MO_LAN_SSH_CACHE" | sed 's/^# Refreshed: //')
    count=$(grep -cvE '^(#|$)' "$_MO_LAN_SSH_CACHE")
    cur_net=$(_mo_lan_network_id)
    cache_net=$(_mo_lan_cache_network)
    if [[ "$cur_net" == "$cache_net" ]]; then
        net_status="%F{green}✓ stable%f"
    else
        net_status="%F{yellow}✗ changed (will refresh on next shell)%f"
    fi

    print -P "%BCache:%b $_MO_LAN_SSH_CACHE"
    print -P "  Age:       ${hours}h ${mins}m"
    print -P "  Refreshed: ${refreshed}"
    print -P "  Hosts:     ${count}"
    print -P "  Network:   ${cache_net} (now: ${cur_net}) — ${net_status}"
    print -P "%BSettings:%b"
    print -P "  TTL:       ${MO_LAN_TTL}s"
    print -P "  Ports:     ${MO_LAN_SSH_PORTS}"
    print -P "  Excludes:  ${MO_LAN_EXCLUDE:-(none)}"
    print -P "%BSSH config:%b"
    if grep -qE '^[[:space:]]*Include[[:space:]]+config\.d/' "$_MO_LAN_SSH_USER_CONFIG" 2>/dev/null; then
        print -P "  %F{green}✓%f ~/.ssh/config has Include line"
    else
        print -P "  %F{yellow}✗%f ~/.ssh/config missing Include — run: %Bmo-lan-ssh setup%b"
    fi
}

_mo_lan_setup() {
    mkdir -p "$_MO_LAN_SSH_USER_CONFIG_DIR"
    chmod 700 "$_MO_LAN_SSH_USER_CONFIG_DIR"

    if [[ ! -f "$_MO_LAN_SSH_USER_CONFIG" ]]; then
        touch "$_MO_LAN_SSH_USER_CONFIG"
        chmod 600 "$_MO_LAN_SSH_USER_CONFIG"
        echo "Created ${_MO_LAN_SSH_USER_CONFIG}"
    fi
    if ! grep -qE '^[[:space:]]*Include[[:space:]]+config\.d/' "$_MO_LAN_SSH_USER_CONFIG"; then
        local tmp="${_MO_LAN_SSH_USER_CONFIG}.tmp"
        { echo "Include config.d/*"; echo ""; cat "$_MO_LAN_SSH_USER_CONFIG"; } > "$tmp"
        chmod 600 "$tmp"
        mv "$tmp" "$_MO_LAN_SSH_USER_CONFIG"
        echo "Added 'Include config.d/*' to ${_MO_LAN_SSH_USER_CONFIG}"
    else
        echo "Include line already in ${_MO_LAN_SSH_USER_CONFIG}"
    fi

    if [[ -f "$HOME/.ssh/id_ed25519" || -f "$HOME/.ssh/id_rsa" || -f "$HOME/.ssh/id_ecdsa" ]]; then
        echo "SSH key present in ~/.ssh/"
    else
        echo "No SSH key found. Run: ssh-keygen -t ed25519"
    fi

    echo "Running first discovery (foreground)..."
    if zsh "$_MO_LAN_SSH_DISCOVER"; then
        _mo_lan_maybe_write_sshconf
        local count
        count=$(grep -cvE '^(#|$)' "$_MO_LAN_SSH_CACHE")
        echo "Setup complete: ${count} hosts discovered. Open a new terminal to see the s-<host> aliases."
    else
        echo "Discovery failed. Check 'mo-lan-ssh status' for details."
        return 1
    fi
}

mo-lan-ssh() {
    local sub="${1:-help}"
    shift 2>/dev/null

    case "$sub" in
        list)
            [[ -f "$_MO_LAN_SSH_CACHE" ]] || {
                echo "mo-lan-ssh: no cache yet — run: mo-lan-ssh refresh" >&2
                return 1
            }
            grep -vE '^(#|$)' "$_MO_LAN_SSH_CACHE"
            ;;
        refresh)
            local bg=false
            local arg
            for arg in "$@"; do
                case "$arg" in
                    --background) bg=true ;;
                    -f|--force) : ;;   # currently a no-op (refresh always rebuilds)
                esac
            done
            if $bg; then
                _mo_lan_refresh_async
                echo "Discovery running in background."
                return
            fi
            if zsh "$_MO_LAN_SSH_DISCOVER"; then
                _mo_lan_maybe_write_sshconf
                local count
                count=$(grep -cvE '^(#|$)' "$_MO_LAN_SSH_CACHE")
                echo "Refresh complete: ${count} hosts. Open a new terminal for updated aliases."
            else
                return $?
            fi
            ;;
        status)
            _mo_lan_status
            ;;
        setup)
            _mo_lan_setup
            ;;
        help|-h|--help)
            cat <<'EOF'
Usage: mo-lan-ssh <command>

Commands:
  list                    Print cached LAN hosts (one per line, with :port if non-22)
  refresh [-f]            Refresh now (foreground)
  refresh --background    Refresh in background, return immediately
  status                  Show cache age, network ID, host count, SSH config state
  setup                   Bootstrap: ensure ~/.ssh/config has Include line + first refresh
  help                    Show this message

Env-var configuration (set in ~/.zshrc):
  MO_LAN_TTL              Cache freshness window in seconds (default: 86400)
  MO_LAN_SSH_PORTS        Comma-list of ports to probe (default: 22)
  MO_LAN_PROBE_TIMEOUT    Per-port probe timeout in seconds (default: 2)
  MO_LAN_PROBE_PARALLEL   Concurrent host probes (default: 20)
  MO_LAN_EXCLUDE          Comma-list of hostnames to never alias
  MO_LAN_SUBNET           Override discovery subnet (e.g. 10.0.1.0/24)
  MO_LAN_DNS_SERVER       Override DNS server for AXFR
  MO_LAN_DNS_ZONE         Override DNS zone for AXFR
  MO_LAN_VERBOSE          Print [mo-lan-ssh] log lines on background refresh (default: false)
EOF
            ;;
        *)
            echo "mo-lan-ssh: unknown command '$sub' — see 'mo-lan-ssh help'" >&2
            return 1
            ;;
    esac
}
